#开发环境
breakpoint:
  upload:
    dir: /Users/tuojinguo/Documents/Mydoc/common/data/uploads/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 20 971 520

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 30
      max-idle: 10
      max-wait: 10000
    timeout: 0
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
